# Generated by Django 4.0.6 on 2022-08-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0002_post_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
