# Generated by Django 4.0.6 on 2022-08-20 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0021_alter_post_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='page3.post')),
            ],
        ),
    ]
