# Generated by Django 4.0.6 on 2022-08-06 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0006_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
