# Generated by Django 4.0.6 on 2022-08-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0017_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discord_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitch_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
