# Generated by Django 4.0.6 on 2022-08-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0027_videos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
