# Generated by Django 4.0.6 on 2022-08-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0030_post_image_id_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_id_list',
        ),
    ]
