# Generated by Django 3.2.15 on 2022-09-27 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page3', '0035_alter_imagefiles_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('Val', 'Valorant'), ('COD', 'Call of Duty'), ('LOL', 'League of Legends'), ('CS Go', 'Counter Shit: GO')], max_length=50)),
                ('server', models.CharField(choices=[('Val', [('APAC', 'Asia Pacific'), ('EMEA', 'Europe'), ('NA', 'North America(meaning shit)'), ('JA', 'Japan')]), ('COD', [('APAC', 'Asia Pacific'), ('EMEA', 'Europe'), ('NA', 'North America(meaning shit)')]), ('LOL', [('APAC', 'Asia Pacific'), ('EMEA', 'Europe'), ('NA', 'North America(meaning shit)')]), ('CS', [('EMEA', 'Europe'), ('NA', 'North America(meaning shit)')])], max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
