# Generated by Django 3.2.15 on 2022-09-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0037_gameprofile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='user_status',
            field=models.CharField(choices=[('Looking for teams', 'Looking for teams'), ('Looking for talent', 'Looking for talent'), ('none', 'none')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='game',
            field=models.CharField(choices=[('Valorant', 'Valorant'), ('Call of Duty', 'Call of Duty'), ('League of Legends', 'League of Legends'), ('Counter Shit: GO', 'Counter Shit: GO')], max_length=50),
        ),
    ]
