# Generated by Django 3.2.15 on 2022-10-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0041_auto_20221004_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='', max_length=255),
        ),
    ]
