# Generated by Django 3.2.15 on 2022-10-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0042_auto_20221004_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='post',
            field=models.ManyToManyField(blank=True, default=None, related_name='tagged_posts', to='page3.Post'),
        ),
    ]
