# Generated by Django 4.0.6 on 2022-08-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0003_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='value',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
    ]
