# Generated by Django 4.0.6 on 2022-08-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0004_category_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='value',
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
