# Generated by Django 4.0.6 on 2022-08-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0005_remove_category_value_category_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
