# Generated by Django 4.0.6 on 2022-08-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0013_post_like_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
