# Generated by Django 4.0.6 on 2022-08-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0022_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='post_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
