# Generated by Django 4.0.6 on 2022-08-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0023_alter_replies_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='reply_to',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
