# Generated by Django 4.0.6 on 2022-08-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0031_remove_post_image_id_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_images',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
